# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-22 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_quotes_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='likes',
        ),
    ]
